python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 0
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 0
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 1
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 1
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 2
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 2
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 3
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 3
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 4
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 4
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 5
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 5
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 6
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 6
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 7
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 7
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 8
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 8
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 9
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 9
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 10
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 10
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 11
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 11
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 12
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 12
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 13
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 13
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 14
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 14
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 15
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 15
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 16
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 16
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 17
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 17
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 18
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 18
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 19
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 19
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 20
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 20
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 21
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 21
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 22
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 22
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 23
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 23
python .\src\generate_dataet_NPInter2_RPI2241_mutual_interaction_study.py --projectName %1 --interactionDatasetName RPI2241 --createBalanceDataset 0 --number 24
python .\src\train_with_twoDataset_NPInter2_RPI2241_mutual_interaction_study.py --trainingName %1 --trainingDatasetName %1_inMemory_train_mutualInteractionStudy --testingDatasetName %1_inMemory_test_mutualInteractionStudy --interactionDatasetName RPI2241 --fold 24